# Generated by Django 6.0.6 on 2026-06-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_type', models.CharField(choices=[('SIX_SIGMA', 'Six Sigma'), ('LEAN', 'Lean'), ('KAIZEN', 'Kaizen'), ('CAPA', 'CAPA'), ('OTHER', 'Other')], default='SIX_SIGMA', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DEFINE', 'Define'), ('MEASURE', 'Measure'), ('ANALYZE', 'Analyze'), ('IMPROVE', 'Improve'), ('CONTROL', 'Control'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='DEFINE', max_length=20)),
                ('problem_statement', models.TextField()),
                ('goal_statement', models.TextField()),
                ('business_case', models.TextField(blank=True, default='')),
                ('scope_in', models.TextField(blank=True, default='', verbose_name='Scope (In)')),
                ('scope_out', models.TextField(blank=True, default='', verbose_name='Scope (Out)')),
                ('benefits', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('SPONSOR', 'Sponsor'), ('FACILITATOR', 'Facilitator'), ('TEAM_MEMBER', 'Team Member')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Team Member',
                'verbose_name_plural': 'Project Team Members',
                'ordering': ['display_order', 'employee_name'],
            },
        ),
    ]
