# Generated by Django 6.0.6 on 2026-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('project', 'role'), name='unique_leader_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'sponsor')), fields=('project', 'role'), name='unique_sponsor_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'facilitator')), fields=('project', 'role'), name='unique_facilitator_per_project'),
        ),
    ]
