# Generated by Django 6.0.6 on 2026-06-14 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectteammember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteammember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
