# Generated by Django 6.0.6 on 2026-06-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectteammember_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_case', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('goal_statement', models.TextField(blank=True)),
                ('scope_in', models.TextField(blank=True)),
                ('scope_out', models.TextField(blank=True)),
                ('expected_benefits', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('success_metrics', models.TextField(blank=True)),
                ('financial_impact', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charter', to='projects.project')),
            ],
        ),
    ]
