# Generated by Django 6.0.6 on 2026-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcharter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='project',
            name='business_case',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scope_in',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scope_out',
        ),
    ]
