# Generated by Django 6.0.6 on 2026-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_benefits_remove_project_business_case_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcharter',
            options={'ordering': ['project']},
        ),
        migrations.RemoveField(
            model_name='projectcharter',
            name='expected_benefits',
        ),
        migrations.RemoveField(
            model_name='projectcharter',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectcharter',
            name='target_completion_date',
        ),
        migrations.AddField(
            model_name='projectcharter',
            name='benefits',
            field=models.TextField(blank=True, help_text='Expected business benefits from this project.'),
        ),
    ]
